addons:
  sonarqube: true
language: java
sudo: required
jdk:
  - oraclejdk7
#cache:
#  directories:
#    - $TRAVIS_BUILD_DIR/libraries
before_install:
  - sudo pip install codecov
install:
  - wget -P libraries/apache-ant-contrib/javalib/ http://central.maven.org/maven2/org/apache/ivy/ivy/2.4.0/ivy-2.4.0.jar
  - mkdir ../document
  - cd ../document
  - wget https://github.com/servicecatalog/documentation/archive/master.zip
  - unzip master.zip
  - mv documentation-master/* .
  - cd ../development
env:
  global:
    - ANT_OPTS=-Xmx4g
    - COMUPTERNAME=travis
    - HOSTNAME=travis
script:
  - jdk_switcher use oraclejdk7
  - ant -lib $TRAVIS_BUILD_DIR/libraries/apache-ant-contrib/javalib -file $TRAVIS_BUILD_DIR/oscm-build/cruisecontrol.xml runTravisUT
#  - ant -lib $TRAVIS_BUILD_DIR/libraries/apache-ant-contrib/javalib -file $TRAVIS_BUILD_DIR/oscm-build/cruisecontrol.xml runTravisIT
  - jdk_switcher use oraclejdk8
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.projectKey=CTMG -Dsonar.projectName=CTMG -Dsonar.projectVersion=16.2 -Dsonar.sources=$TRAVIS_BUILD_DIR -Dsonar.sourceEncoding=UTF-8 -Dsonar.inclusions=**/*.java
after_success:
  - codecov
